//
//  Workspace.swift
//  Packages
//
//  Created by 김동현 on 12/18/25.
//

import ProjectDescription

let workspace = Workspace(
  name: "TestApp",
  projects: [
    "Projects/App",
    "Projects/Feature"
//    "Projects/Core",
//    "Projects/DesignSystem",
//    "Projects/Features/Scene",
//    "Projects/Features/Coordinator",
  ],
//  schemes: [
//    .scheme(
//      name: "Index",
//      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Prod-Index")]),
//      runAction: .runAction(
//        configuration: .release,
//        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
//      ),
//      archiveAction: .archiveAction(configuration: .release),
//      profileAction: .profileAction(configuration: .release),
//      analyzeAction: .analyzeAction(configuration: .release)
//    )
//  ],
//  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
